language: ruby
rvm:
  - 2.2.3
services:
  - redis-server
  - postgresql
before_script:
  - psql -c 'create database voc_test;' -U postgres
  - bundle exec rake db:setup
  - bundle exec rake db:migrate
script:
  - bundle exec rspec
  - bundle exec cucumber -t ~@wip -t ~@social
